name: authentication_repository
description: A starting point for Dart libraries or applications.

environment:
  sdk: '>=2.18.5 <3.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
  very_good_analysis: ^3.1.0
